language: cpp
sudo: required
dist: trusty

addons: &gcc5
  apt:
    packages:
      - libstdc++-5-dev
    sources:
      - ubuntu-toolchain-r-test

matrix:
  include:
    # Build with Linux and gcc.
    # The default gcc compiler does not support C++11 so install a higher version.
    - os: linux
      env: CXX=g++-5

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5
  - export CXX="g++-5"
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y aptitude
  - aptitude search boost
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
 
script:
  - make build
  - make ctests
 