os: Visual Studio 2015

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

build_script:
  - md cmake.bld
  - cd cmake.bld
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - ctest -C Release
